### PR TITLE
RELATED: FET-564 Sonar config

### PR DESCRIPTION
**Pull request by ivanmjartan**

### CODE REVIEW

**Comment by ghost** [comment]
Build succeeded (check pipeline).

**Comment by pbenes** [comment]
extended check sonar

**Comment by yenkins** [comment]
### Sonar scan result
 - No new bug found. Congratulation!

More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=grunt-depmod-check-extended-sonar-PR4

**Comment by ghost** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/grunt-depmod-sonarqube-scan-zuul-el7/1/ : SUCCESS in 36s (non-voting)

**Review by pbenes — APPROVED** [review]

**Comment by yenkins** [comment]
### Sonar scan result
 - No new bug found. Congratulation!

More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=grunt-depmod-gate-PR4

**Comment by ghost** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/grunt-depmod-sonarqube-scan-zuul-el7/2/ : SUCCESS in 38s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/grunt-depmod-fossa-scanning-zuul-el7/1/ : SUCCESS in 1m 44s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/grunt-depmod-merge-compliance-check/3/ : SUCCESS in 16s

**Pull request merged**
