### PR TITLE
RELATED: FET-833 Upgrade packages

### PR DESCRIPTION
**Pull request by pbenes**

### CODE REVIEW

**Comment by ghost** [comment]
Build succeeded (check pipeline).

**Comment by pbenes** [comment]
ok to test

**Comment by ghost** [comment]
Build succeeded (check pipeline).

**Review by anvuong119 — APPROVED** [review]

**Comment by anvuong119** [comment]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=grunt-depmod-gate-PR5

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by ghost** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/grunt-depmod-sonarqube-scan-zuul-gate/1/ : SUCCESS in 50s
- https://checklist.intgdc.com/job/compliance/job/grunt-depmod-fossa-scanning-zuul-el7/2/ : SUCCESS in 1m 32s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/grunt-depmod-merge-compliance-check/4/ : SUCCESS in 18s

**Pull request merged**
